import { useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownToLine, CalendarDays, Check, FileText, MapPin, Plus, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { api, DEFAULT_CAMPUS_TIMEZONE, formatDate, jsonBody } from '../lib/api';
import { Badge, Card, EmptyState, Field, Loading, Notice, PageHeader } from '../components/ui';
import { ActivityBadge, MapPinIcon, PanelTitle, errorText, localDateTimeToUtc, statusTone } from './admin-shared';
import type { AttendanceRow, AuditRow, CorrectionRow, Course, Department, LocationRow, Section, SessionRow, StudentRow } from './admin-shared';

interface EnrollmentRow { student_id:string; course_id:string; section_id:string|null; active:boolean }

export function LocationsPage(){
 const qc=useQueryClient();const [error,setError]=useState('');const [message,setMessage]=useState('');const [edit,setEdit]=useState<LocationRow|null>(null);
 const departments=useQuery({queryKey:['admin-departments'],queryFn:()=>api<Department[]>('/admin/departments')});const courses=useQuery({queryKey:['admin-courses'],queryFn:()=>api<Course[]>('/admin/courses')});const sections=useQuery({queryKey:['admin-sections'],queryFn:()=>api<Section[]>('/admin/sections')});const locations=useQuery({queryKey:['admin-locations'],queryFn:()=>api<LocationRow[]>('/admin/locations')});const sessions=useQuery({queryKey:['admin-sessions'],queryFn:()=>api<{items:SessionRow[]}>('/admin/sessions?limit=200')});const campus=useQuery({queryKey:['campus-health'],queryFn:()=>api<{campus_timezone:string}>('/health/ready'),retry:false});
 const [loc,setLoc]=useState({department_id:'',name:'',latitude:'',longitude:'',radius_m:100,max_accuracy_m:75,active:true});const [schedule,setSchedule]=useState({course_id:'',section_id:'',location_id:'',title:'Class session',starts_at:'',ends_at:'',grace_minutes:10});
 if([departments,courses,sections,locations,sessions,campus].some(q=>q.isLoading))return <Loading label="Loading locations and schedules…"/>;const timezone=campus.data?.campus_timezone||DEFAULT_CAMPUS_TIMEZONE;
 async function createLocation(e:FormEvent){e.preventDefault();setError('');try{await api('/admin/locations',{method:'POST',body:jsonBody({...loc,latitude:Number(loc.latitude),longitude:Number(loc.longitude)})});setMessage('Classroom geofence created.');setLoc({...loc,name:'',latitude:'',longitude:''});await qc.invalidateQueries({queryKey:['admin-locations']});}catch(err){setError(errorText(err));}}
 async function updateLocation(e:FormEvent){e.preventDefault();if(!edit)return;setError('');try{await api(`/admin/locations/${edit.id}`,{method:'PATCH',body:jsonBody(edit)});setEdit(null);setMessage('Classroom and geofence policy updated.');await qc.invalidateQueries({queryKey:['admin-locations']});}catch(err){setError(errorText(err));}}
 async function createSession(e:FormEvent){e.preventDefault();setError('');try{const body={...schedule,section_id:schedule.section_id||null,starts_at:localDateTimeToUtc(schedule.starts_at,timezone),ends_at:localDateTimeToUtc(schedule.ends_at,timezone),grace_minutes:Number(schedule.grace_minutes)};await api('/admin/sessions',{method:'POST',body:jsonBody(body)});setMessage('Class session scheduled.');await qc.invalidateQueries({queryKey:['admin-sessions']});}catch(err){setError(errorText(err));}}
 async function action(row:SessionRow,kind:'cancel'|'finalize'){if(kind==='cancel'&&!window.confirm('Cancel this session? Sessions with attendance records cannot be cancelled.'))return;setError('');try{const res=await api<{created_absences?:number}>(`/admin/sessions/${row.id}/${kind}`,{method:'POST'});setMessage(kind==='cancel'?'Session cancelled.':`Session finalized; ${res.created_absences||0} absence records created.`);await qc.invalidateQueries({queryKey:['admin-sessions']});await qc.invalidateQueries({queryKey:['admin-attendance']});}catch(err){setError(errorText(err));}}
 function useHere(){if(!navigator.geolocation){setError('This browser does not support geolocation. Enter the classroom coordinates manually.');return;}navigator.geolocation.getCurrentPosition(p=>setLoc({...loc,latitude:p.coords.latitude.toFixed(6),longitude:p.coords.longitude.toFixed(6)}),()=>setError('Location permission denied. Enter the coordinates manually.'),{enableHighAccuracy:true,timeout:10000,maximumAge:0});}
 const selectedCourse=courses.data?.find(c=>c.id===schedule.course_id);const allowed=locations.data?.filter(l=>l.active&&(!selectedCourse||l.department_id===selectedCourse.department_id))||[];
 return <main><PageHeader eyebrow="PLACE & TIME" title="Locations & schedules" description={`Classroom geofences and attendance windows. Schedule times use ${timezone}; timestamps are stored as UTC instants and displayed in ${timezone}.`}/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
 <div className="grid-two"><Card><PanelTitle icon={<MapPinIcon/>} eyebrow="GEOFENCE POLICY" title="Add classroom"/><p className="card-intro">The system stores configured classroom coordinates; raw student location readings are discarded after verification.</p><form className="form-grid" onSubmit={createLocation}><Field label="Department"><select required value={loc.department_id} onChange={e=>setLoc({...loc,department_id:e.target.value})}><option value="">Choose department</option>{departments.data?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Location name"><input required maxLength={160} value={loc.name} onChange={e=>setLoc({...loc,name:e.target.value})} placeholder="Science Hall · Room 204"/></Field><div className="form-two"><Field label="Latitude"><input type="number" step="any" min="-90" max="90" required value={loc.latitude} onChange={e=>setLoc({...loc,latitude:e.target.value})}/></Field><Field label="Longitude"><input type="number" step="any" min="-180" max="180" required value={loc.longitude} onChange={e=>setLoc({...loc,longitude:e.target.value})}/></Field></div><button type="button" className="text-link inline-button" onClick={useHere}><MapPin size={15}/> Use this device's coordinates</button><div className="form-two"><Field label="Allowed radius (metres)"><input type="number" min="1" max="5000" value={loc.radius_m} onChange={e=>setLoc({...loc,radius_m:Number(e.target.value)})}/></Field><Field label="Maximum accepted accuracy (metres)"><input type="number" min="1" max="1000" value={loc.max_accuracy_m} onChange={e=>setLoc({...loc,max_accuracy_m:Number(e.target.value)})}/></Field></div><div className="form-action"><button className="button button-primary" disabled={!departments.data?.length}><Plus size={16}/> Save classroom</button></div></form></Card>
 <Card><PanelTitle icon={<CalendarDays size={17}/>} eyebrow="CLASS SCHEDULE" title="Schedule a session"/><p className="card-intro">Students must match the course/section, schedule window, geofence, liveness and enrolled face template.</p><form className="form-grid" onSubmit={createSession}><Field label="Course"><select required value={schedule.course_id} onChange={e=>setSchedule({...schedule,course_id:e.target.value,section_id:'',location_id:''})}><option value="">Choose course</option>{courses.data?.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.course_code} · {c.name}</option>)}</select></Field><div className="form-two"><Field label="Section"><select value={schedule.section_id} onChange={e=>setSchedule({...schedule,section_id:e.target.value})}><option value="">All sections</option>{sections.data?.filter(s=>s.course_id===schedule.course_id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Classroom"><select required value={schedule.location_id} onChange={e=>setSchedule({...schedule,location_id:e.target.value})}><option value="">Choose location</option>{allowed.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field></div><Field label="Session title"><input required maxLength={180} value={schedule.title} onChange={e=>setSchedule({...schedule,title:e.target.value})}/></Field><div className="form-two"><Field label={`Starts (${timezone})`}><input required type="datetime-local" value={schedule.starts_at} onChange={e=>setSchedule({...schedule,starts_at:e.target.value})}/></Field><Field label={`Ends (${timezone})`}><input required type="datetime-local" value={schedule.ends_at} onChange={e=>setSchedule({...schedule,ends_at:e.target.value})}/></Field></div><Field label="Grace period (minutes)"><input type="number" min="0" max="180" value={schedule.grace_minutes} onChange={e=>setSchedule({...schedule,grace_minutes:Number(e.target.value)})}/></Field><div className="form-action"><button className="button button-primary" disabled={!allowed.length}><Plus size={16}/> Schedule class</button></div></form>{!allowed.length&&<p className="inline-hint">Create an active location in the selected course department.</p>}</Card></div>
 <Card className="data-card"><div className="card-heading"><div><span className="eyebrow">GEOGRAPHIC POLICY</span><h2>Configured classrooms</h2></div><Badge>{locations.data?.length||0} locations</Badge></div>{locations.data?.length?<div className="location-grid">{locations.data.map(l=><div className="location-tile" key={l.id}><div className="tile-icon"><MapPinIcon/></div><div className="tile-copy"><strong>{l.name}</strong><small>{departments.data?.find(d=>d.id===l.department_id)?.name}</small><span>{l.latitude.toFixed(5)}, {l.longitude.toFixed(5)}</span></div><div className="tile-policy"><Badge tone={l.active?'success':'neutral'}>{l.active?'Active':'Inactive'}</Badge><small>Radius {l.radius_m} m · accuracy ≤ {l.max_accuracy_m} m</small><button className="text-action" onClick={()=>setEdit({...l})}>Edit policy</button></div></div>)}</div>:<EmptyState title="No classroom locations" message="Create a location before scheduling a class."/>}</Card>
 <Card className="data-card"><div className="card-heading"><div><span className="eyebrow">SCHEDULED CLASSES</span><h2>Class sessions</h2><p>Windows close after the grace period. Finalization creates absent records for enrolled students without a record.</p></div></div>{sessions.data?.items.length?<div className="table-wrap"><table><thead><tr><th>Class</th><th>Classroom</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>{sessions.data.items.map(s=><tr key={s.id}><td><strong>{s.course_code} · {s.title}</strong><small className="cell-sub">{s.course_name}</small></td><td>{s.location_name}</td><td>{formatDate(s.starts_at,timezone)}<small className="cell-sub">Ends {formatDate(s.ends_at,timezone)} · {s.grace_minutes} min grace</small></td><td><Badge tone={s.cancelled?'danger':s.finalized?'success':'info'}>{s.cancelled?'Cancelled':s.finalized?'Finalized':'Scheduled'}</Badge></td><td><div className="row-actions">{!s.cancelled&&!s.finalized&&<><button className="text-action" onClick={()=>void action(s,'finalize')}>Finalize absences</button><button className="text-action danger-text" onClick={()=>void action(s,'cancel')}>Cancel</button></>}</div></td></tr>)}</tbody></table></div>:<EmptyState title="No sessions scheduled" message="Create a session after adding a course and classroom."/>}</Card>
 {edit&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setEdit(null)}><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-heading"><h2>Update geofence policy</h2><button className="icon-button" aria-label="Close" onClick={()=>setEdit(null)}><X size={18}/></button></div><form className="form-grid" onSubmit={updateLocation}><Field label="Location name"><input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="Department"><select value={edit.department_id} onChange={e=>setEdit({...edit,department_id:e.target.value})}>{departments.data?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><div className="form-two"><Field label="Latitude"><input type="number" step="any" value={edit.latitude} onChange={e=>setEdit({...edit,latitude:Number(e.target.value)})}/></Field><Field label="Longitude"><input type="number" step="any" value={edit.longitude} onChange={e=>setEdit({...edit,longitude:Number(e.target.value)})}/></Field></div><div className="form-two"><Field label="Radius (metres)"><input type="number" min="1" max="5000" value={edit.radius_m} onChange={e=>setEdit({...edit,radius_m:Number(e.target.value)})}/></Field><Field label="Maximum accuracy (metres)"><input type="number" min="1" max="1000" value={edit.max_accuracy_m} onChange={e=>setEdit({...edit,max_accuracy_m:Number(e.target.value)})}/></Field></div><label className="check-row"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Location is active</label><button className="button button-primary">Save policy</button></form></section></div>}
 </main>;
}

export function AdminAttendancePage(){
 const qc=useQueryClient();const [courseId,setCourseId]=useState('');const [status,setStatus]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [fix,setFix]=useState({student_id:'',session_id:'',status:'present',reason:''});
 const courses=useQuery({queryKey:['admin-courses'],queryFn:()=>api<Course[]>('/admin/courses')});const students=useQuery({queryKey:['admin-students'],queryFn:()=>api<{items:StudentRow[]}>('/admin/students?limit=200')});const sessions=useQuery({queryKey:['admin-sessions'],queryFn:()=>api<{items:SessionRow[]}>('/admin/sessions?limit=200')});const enrollments=useQuery({queryKey:['admin-enrollments'],queryFn:()=>api<EnrollmentRow[]>('/admin/enrollments')});const records=useQuery({queryKey:['admin-attendance',courseId,status],queryFn:()=>api<{items:AttendanceRow[];total:number}>(`/admin/attendance?limit=300${courseId?`&course_id=${courseId}`:''}${status?`&status=${status}`:''}`)});
 if([courses,students,sessions,enrollments,records].some(q=>q.isLoading))return <Loading label="Loading attendance records…"/>;
 async function correct(e:FormEvent){e.preventDefault();setError('');try{await api('/admin/attendance/correct',{method:'POST',body:jsonBody(fix)});setMessage('Attendance corrected and audit event recorded.');await qc.invalidateQueries({queryKey:['admin-attendance']});await qc.invalidateQueries({queryKey:['student-dashboard']});}catch(err){setError(errorText(err));}}
 const selectedSession=sessions.data?.items.find(s=>s.id===fix.session_id);const eligibleStudents=students.data?.items.filter(s=>!selectedSession||enrollments.data?.some(enrollment=>enrollment.active&&enrollment.student_id===s.id&&enrollment.course_id===selectedSession.course_id&&(!selectedSession.section_id||enrollment.section_id===selectedSession.section_id)))||[];const eligibleSessions=sessions.data?.items.filter(s=>!s.cancelled&&(!fix.student_id||enrollments.data?.some(enrollment=>enrollment.active&&enrollment.student_id===fix.student_id&&enrollment.course_id===s.course_id&&(!s.section_id||enrollment.section_id===s.section_id))))||[];
 const reportParams=new URLSearchParams();if(courseId)reportParams.set('course_id',courseId);if(status)reportParams.set('status',status);const reportSuffix=reportParams.size?`?${reportParams.toString()}`:'';const csv=`/api/v1/admin/reports/attendance.csv${reportSuffix}`;const printable=`/api/v1/admin/reports/print${reportSuffix}`;
 return <main><PageHeader eyebrow="REPORTING & REVIEW" title="Attendance & reports" description="Search institutional records, export CSV and record reasoned attendance corrections." actions={<><a className="button button-secondary" href={csv}><ArrowDownToLine size={16}/> Export CSV</a><a className="button button-secondary" href={printable} target="_blank" rel="noreferrer"><FileText size={16}/> Print view</a></>}/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
 <Card className="data-card"><div className="filter-bar"><label className="field"><span className="field-label">Course</span><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">All courses</option>{courses.data?.map(c=><option key={c.id} value={c.id}>{c.course_code} · {c.name}</option>)}</select></label><label className="field"><span className="field-label">Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['present','late','absent','excused'].map(s=><option key={s}>{s}</option>)}</select></label><div className="filter-count"><strong>{records.data?.total||0}</strong> records</div></div>{records.data?.items.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Session</th><th>Status</th><th>Recorded</th><th>Correction</th></tr></thead><tbody>{records.data.items.map(r=><tr key={r.id}><td><strong>{r.student_name}</strong><small className="cell-sub">{r.student_number}</small></td><td><strong>{r.course_code}</strong><small className="cell-sub">{r.course_name}</small></td><td><code className="short-id">{r.session_id.slice(0,8)}</code></td><td><Badge tone={statusTone(r.status)}>{r.status}</Badge></td><td>{formatDate(r.marked_at)}</td><td><button className="text-action" onClick={()=>setFix({student_id:r.student_id,session_id:r.session_id,status:r.status,reason:''})}>Correct</button>{r.reason&&<small className="cell-sub">{r.reason}</small>}</td></tr>)}</tbody></table></div>:<EmptyState title="No matching attendance records" message="Attendance records appear after a session is finalized or students complete verification."/>}</Card>
 <Card className="correction-form-card"><div className="card-heading"><div><span className="eyebrow">MANUAL REVIEW</span><h2>Correct an attendance status</h2><p>Corrections are attributed to your administrator account and retained in the audit trail.</p></div><ShieldCheck size={19} className="muted-icon"/></div><form className="form-grid correction-grid" onSubmit={correct}><Field label="Student"><select required value={fix.student_id} onChange={e=>setFix({...fix,student_id:e.target.value})}><option value="">Choose student</option>{eligibleStudents.map(s=><option key={s.id} value={s.id}>{s.student_number} · {s.full_name}</option>)}</select></Field><Field label="Class session"><select required value={fix.session_id} onChange={e=>setFix({...fix,session_id:e.target.value,student_id:''})}><option value="">Choose session</option>{eligibleSessions.map(s=><option key={s.id} value={s.id}>{s.course_code} · {s.title} · {formatDate(s.starts_at)}</option>)}</select></Field><Field label="Correct status"><select value={fix.status} onChange={e=>setFix({...fix,status:e.target.value})}>{['present','late','absent','excused'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Reason"><input required minLength={5} maxLength={1000} value={fix.reason} onChange={e=>setFix({...fix,reason:e.target.value})} placeholder="Document the reason"/></Field><button className="button button-primary"><Check size={16}/> Save correction</button></form></Card>
 </main>;
}

export function CorrectionsPage(){
 const qc=useQueryClient();const [status,setStatus]=useState('pending');const [error,setError]=useState('');const [message,setMessage]=useState('');const query=useQuery({queryKey:['admin-corrections',status],queryFn:()=>api<CorrectionRow[]>(`/admin/corrections?status=${status}`)});
 async function decide(r:CorrectionRow,approved:boolean){const note=window.prompt(approved?'Add an approval note:':'Add a reason for rejection:');if(note===null)return;if(note.trim().length<3){setError('Enter at least three characters for the decision note.');return;}setError('');try{await api(`/admin/corrections/${r.id}/resolve`,{method:'POST',body:jsonBody({approved,decision_reason:note})});setMessage(`Request ${approved?'approved':'rejected'}; the decision was audited.`);await qc.invalidateQueries({queryKey:['admin-corrections']});await qc.invalidateQueries({queryKey:['admin-attendance']});}catch(e){setError(errorText(e));}}
 if(query.isLoading)return <Loading label="Loading correction requests…"/>;
 return <main><PageHeader eyebrow="MANUAL REVIEW" title="Correction review" description="Review student disputes and teacher-submitted proposals. Approved changes retain an audit trail." actions={<label className="filter-select"><span>Queue</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label>}/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}{query.data?.length?<div className="correction-list">{query.data.map(r=><Card className="correction-item" key={r.id}><div className="correction-item-top"><div><Badge tone={statusTone(r.status)}>{r.status}</Badge><span className="correction-date">Submitted {formatDate(r.created_at)}</span></div><code>{r.id.slice(0,8)}</code></div><h2>{r.student_name} <small>({r.student_number})</small></h2><p className="correction-context">{r.course_name} · Session {r.session_id.slice(0,8)}</p><div className="correction-reason"><span>REQUESTED STATUS</span><Badge tone={statusTone(r.requested_status)}>{r.requested_status}</Badge><span>SUBMITTED BY {r.submitted_by}</span><p>{r.reason}</p></div>{r.decision_reason&&<div className="review-note"><strong>Decision note</strong><p>{r.decision_reason}</p></div>}{r.status==='pending'&&<div className="correction-actions"><button className="button button-primary" onClick={()=>void decide(r,true)}><Check size={16}/> Approve & apply</button><button className="button button-secondary" onClick={()=>void decide(r,false)}><X size={16}/> Reject</button></div>}</Card>)}</div>:<Card><EmptyState title={`No ${status} requests`} message={status==='pending'?'New student disputes and teacher proposals will appear here.':'There are no requests in this state.'}/></Card>}</main>;
}

export function AuditPage(){const query=useQuery({queryKey:['admin-audit'],queryFn:()=>api<AuditRow[]>('/admin/audit?limit=300')});if(query.isLoading)return <Loading label="Loading audit trail…"/>;return <main><PageHeader eyebrow="SECURITY & ACCOUNTABILITY" title="Audit trail" description="Sensitive account, attendance and administrative events." actions={<button className="button button-secondary" onClick={()=>void query.refetch()}><RefreshCw size={15}/> Refresh</button>}/><Notice kind="info">Audit entries omit passwords, cookies, raw face templates, uploaded frames and raw student GPS coordinates.</Notice><Card className="data-card"><div className="table-wrap"><table><thead><tr><th>Action</th><th>Actor</th><th>Record</th><th>Details</th><th>Time</th></tr></thead><tbody>{query.data?.map(r=><tr key={r.id}><td><strong>{r.action}</strong></td><td><code>{r.actor_user_id?.slice(0,8)||'System'}</code></td><td>{r.entity_type}<small className="cell-sub">{r.entity_id?.slice(0,8)||'—'}</small></td><td><code className="audit-details">{JSON.stringify(r.details)}</code></td><td>{formatDate(r.created_at)}</td></tr>)}</tbody></table></div>{!query.data?.length&&<EmptyState title="No audit events" message="Administrative and verification events appear as actions occur."/>}</Card></main>;}

export function SystemPage(){
 const qc=useQueryClient();const health=useQuery({queryKey:['health'],queryFn:()=>api<Record<string,any>>('/health/ready'),retry:false,refetchInterval:60_000});const policy=useQuery({queryKey:['admin-settings'],queryFn:()=>api<{low_attendance_threshold:number}>('/admin/settings')});const [value,setValue]=useState<number|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');
 async function save(e:FormEvent){e.preventDefault();try{await api('/admin/settings',{method:'PUT',body:jsonBody({low_attendance_threshold:value??policy.data?.low_attendance_threshold??75})});setMessage('Default threshold saved for new courses. Existing courses retain their separately configured value.');await qc.invalidateQueries({queryKey:['admin-settings']});}catch(err){setError(errorText(err));}}
 if(health.isLoading||policy.isLoading)return <Loading label="Checking system readiness…"/>;const vision=health.data?.vision_models;
 return <main><PageHeader eyebrow="APPLICATION GOVERNANCE" title="Policy & system health" description="Review local-service readiness, attendance defaults and privacy controls." actions={<a className="button button-secondary" href="/api/v1/docs" target="_blank" rel="noreferrer"><FileText size={16}/> API documentation</a>}/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
 <div className="grid-two"><Card><PanelTitle icon={<ShieldCheck size={17}/>} eyebrow="ATTENDANCE POLICY" title="Default threshold"/><p className="card-intro">Course thresholds drive shared percentage, low-attendance alert and report calculations. Update individual courses under Academic setup.</p><form className="form-grid" onSubmit={save}><Field label="Minimum required attendance (%)"><input type="number" min="0" max="100" step="0.5" value={value??policy.data?.low_attendance_threshold??75} onChange={e=>setValue(Number(e.target.value))}/></Field><button className="button button-primary"><Check size={16}/> Save default policy</button></form><div className="policy-rules"><strong>Calculation rules</strong><ul><li>Present and late count as attended.</li><li>Excused and cancelled sessions are excluded from the denominator.</li><li>A missing record after close counts as absent.</li><li>No percentage is shown before an eligible session ends.</li></ul></div></Card>
 <Card><PanelTitle icon={<ActivityBadge/>} eyebrow="READINESS" title="Local services"/><div className="system-status-list"><div><span><i className={`status-dot ${health.isError?'status-red':'status-green'}`}/> API</span><Badge tone={health.isError?'danger':'success'}>{health.isError?'Unavailable':'Responding'}</Badge></div><div><span><i className={`status-dot ${health.data?.database==='connected'?'status-green':'status-red'}`}/> Database</span><Badge tone={health.data?.database==='connected'?'success':'danger'}>{health.data?.database||'Unavailable'}</Badge></div><div><span><i className={`status-dot ${vision?.ready?'status-green':'status-amber'}`}/> Face model weights</span><Badge tone={vision?.ready?'success':'warning'}>{vision?.ready?'Verified':'Missing or invalid'}</Badge></div><div><span><i className={`status-dot ${vision?.biometric_storage_key_configured?'status-green':'status-red'}`}/> Biometric encryption key</span><Badge tone={vision?.biometric_storage_key_configured?'success':'danger'}>{vision?.biometric_storage_key_configured?'Valid':'Missing or invalid'}</Badge></div><div><span><i className="status-dot status-green"/> Inference</span><strong>Local CPU</strong></div><div><span><i className="status-dot status-green"/> Campus timezone</span><strong>{health.data?.campus_timezone||DEFAULT_CAMPUS_TIMEZONE}</strong></div></div>{vision?.models&&<div className="model-file-list">{Object.values(vision.models).map((item:any)=><div key={item.file}><span>{item.file}</span><Badge tone={item.checksum_valid?'success':item.installed?'danger':'warning'}>{item.checksum_valid?'Verified':item.installed?'Checksum invalid':'Missing'}</Badge></div>)}</div>}<div className="code-callout"><strong>Install after reviewing the model card:</strong><code>cd backend<br/>python -m app.cli install-models --accept-model-terms<br/>python -m app.cli model-check</code></div></Card></div>
 <div className="grid-two lower-grid"><Card><PanelTitle icon={<ShieldCheck size={17}/>} eyebrow="PRIVACY & RETENTION" title="Biometric controls"/><ul className="help-list"><li>Face embeddings are encrypted at rest with a separate Fernet key.</li><li>Camera frames are processed in memory and are not saved to the database or logs.</li><li>Students can delete their own template; administrators can reset it.</li><li>Only calculated distance and reported accuracy are retained for location attempts.</li><li>Retention cleanup is an explicit CLI operation; its default mode is dry-run.</li></ul><p className="small-note">Review <code>models/MODEL_CARD.md</code>, <code>docs/PRIVACY_AND_SECURITY.md</code> and <code>docs/OPERATIONS.md</code> on the application host.</p></Card><Card><PanelTitle icon={<FileText size={17}/>} eyebrow="OPERATIONS" title="Backup & recovery"/><p className="card-intro">Run from the repository root. Restore only into a new empty target selected by the private DATABASE_URL; never restore into production.</p><div className="code-callout"><code>backend/.venv/bin/python scripts/backup_db.py --output data/backup-UTC.backup<br/>backend/.venv/bin/python scripts/restore_db.py --source data/backup-UTC.backup --confirm-target NEW_EMPTY_DATABASE_NAME</code></div><p className="small-note">Model checksums and license notices live in <code>models/MODEL_CARD.md</code>. Troubleshooting steps are in <code>docs/TROUBLESHOOTING.md</code>.</p></Card></div>
 </main>;
}
