import { useEffect, useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Pencil, Plus, Search, ShieldCheck, UserPlus, Users, BookOpen, CalendarDays } from 'lucide-react';
import { api, jsonBody } from '../lib/api';
import { Badge, Card, EmptyState, Field, Loading, Notice, PageHeader } from '../components/ui';
import { Modal, PanelTitle, errorText } from './admin-shared';
import type { Course, Department, FormResult, Section, Semester, StudentRow, TeacherRow, Year } from './admin-shared';

export function PeoplePage(){
 const qc=useQueryClient();const [search,setSearch]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [invite,setInvite]=useState<FormResult|null>(null);const [editStudent,setEditStudent]=useState<StudentRow|null>(null);const [editTeacher,setEditTeacher]=useState<TeacherRow|null>(null);
 const departments=useQuery({queryKey:['admin-departments'],queryFn:()=>api<Department[]>('/admin/departments')});
 const students=useQuery({queryKey:['admin-students',search],queryFn:()=>api<{items:StudentRow[]}>('/admin/students?limit=200'+(search?`&q=${encodeURIComponent(search)}`:''))});
 const teachers=useQuery({queryKey:['admin-teachers',search],queryFn:()=>api<{items:TeacherRow[]}>('/admin/teachers?limit=200'+(search?`&q=${encodeURIComponent(search)}`:''))});
 const [student,setStudent]=useState({email:'',full_name:'',student_number:'',department_id:'',program:''});const [teacher,setTeacher]=useState({email:'',full_name:'',employee_number:'',department_id:''});
 async function create(path:string,data:unknown,label:string){setError('');setMessage('');setInvite(null);try{const res=await api<FormResult>(path,{method:'POST',body:jsonBody(data)});setInvite(res);setMessage(label);await qc.invalidateQueries({queryKey:[path.includes('students')?'admin-students':'admin-teachers']});return true;}catch(e){setError(errorText(e));return false;}}
 async function onStudent(e:FormEvent){e.preventDefault();if(await create('/admin/students',student,'Student account invited. Share the activation link privately.'))setStudent({email:'',full_name:'',student_number:'',department_id:'',program:''});}
 async function onTeacher(e:FormEvent){e.preventDefault();if(await create('/admin/teachers',teacher,'Teacher account invited. Share the activation link privately.'))setTeacher({email:'',full_name:'',employee_number:'',department_id:''});}
 async function status(userId:string,active:boolean){if(!window.confirm(`${active?'Deactivate':'Reactivate'} this account?`))return;setError('');try{await api(`/admin/users/${userId}/status`,{method:'PATCH',body:jsonBody({active:!active})});setMessage('Account status updated.');await qc.invalidateQueries({queryKey:['admin-students']});await qc.invalidateQueries({queryKey:['admin-teachers']});}catch(e){setError(errorText(e));}}
 async function reset(userId:string){if(!window.confirm('Issue a one-time password reset link? Existing sessions will be signed out.'))return;try{setInvite(await api<FormResult>(`/admin/users/${userId}/password-reset`,{method:'POST'}));setMessage('Password reset link issued. Share it only with the account owner.');}catch(e){setError(errorText(e));}}
 async function deleteTemplate(row:StudentRow){if(!window.confirm(`Delete the encrypted face template for ${row.full_name}? The student must enroll again.`))return;try{await api(`/admin/students/${row.id}/face-template`,{method:'DELETE'});setMessage('Face template deleted.');await qc.invalidateQueries({queryKey:['admin-students']});}catch(e){setError(errorText(e));}}
 async function saveStudent(e:FormEvent){e.preventDefault();if(!editStudent)return;try{await api(`/admin/students/${editStudent.id}`,{method:'PATCH',body:jsonBody({email:editStudent.email,full_name:editStudent.full_name,student_number:editStudent.student_number,department_id:editStudent.department_id,program:editStudent.program})});setEditStudent(null);setMessage('Student record updated.');await qc.invalidateQueries({queryKey:['admin-students']});}catch(err){setError(errorText(err));}}
 async function saveTeacher(e:FormEvent){e.preventDefault();if(!editTeacher)return;try{await api(`/admin/teachers/${editTeacher.id}`,{method:'PATCH',body:jsonBody({email:editTeacher.email,full_name:editTeacher.full_name,employee_number:editTeacher.employee_number,department_id:editTeacher.department_id})});setEditTeacher(null);setMessage('Teacher record updated.');await qc.invalidateQueries({queryKey:['admin-teachers']});}catch(err){setError(errorText(err));}}
 if(departments.isLoading||students.isLoading||teachers.isLoading)return <Loading label="Loading campus accounts…"/>;
 return <main><PageHeader eyebrow="ADMINISTRATION" title="People & accounts" description="Register students and teachers, manage access and issue secure activation or reset links." actions={<span className="secure-label"><ShieldCheck size={16}/> One-time invitations</span>}/>
 {message&&<Notice kind="success">{message}{invite&&<div className="invite-box"><strong>One-time activation link</strong><code>{window.location.origin}{invite.activation_path}</code><button className="button button-secondary button-small" onClick={()=>void navigator.clipboard?.writeText(`${window.location.origin}${invite.activation_path}`)}><Check size={14}/> Copy link</button><small>Expires in {invite.expires_in_days??invite.expires_in_hours+' hours'}. Share directly; the token is shown once.</small></div>}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
 <div className="grid-two people-create-grid">
 <Card><PanelTitle icon={<UserPlus size={17}/>} eyebrow="STUDENT REGISTRATION" title="Add a student"/><form className="form-grid" onSubmit={onStudent}><Field label="Full name"><input required value={student.full_name} onChange={e=>setStudent({...student,full_name:e.target.value})}/></Field><Field label="Student ID"><input required value={student.student_number} onChange={e=>setStudent({...student,student_number:e.target.value})}/></Field><Field label="Email address"><input required type="email" value={student.email} onChange={e=>setStudent({...student,email:e.target.value})}/></Field><Field label="Department"><select required value={student.department_id} onChange={e=>setStudent({...student,department_id:e.target.value})}><option value="">Choose department</option>{departments.data?.map(d=><option key={d.id} value={d.id}>{d.name} ({d.code})</option>)}</select></Field><Field label="Program"><input value={student.program} onChange={e=>setStudent({...student,program:e.target.value})} placeholder="Computer Science"/></Field><div className="form-action"><button className="button button-primary" disabled={!departments.data?.length}><Plus size={16}/> Create student</button></div></form>{!departments.data?.length&&<p className="inline-hint">Add a department in Academic setup first.</p>}</Card>
 <Card><PanelTitle icon={<Users size={17}/>} eyebrow="TEACHER REGISTRATION" title="Add a teacher"/><form className="form-grid" onSubmit={onTeacher}><Field label="Full name"><input required value={teacher.full_name} onChange={e=>setTeacher({...teacher,full_name:e.target.value})}/></Field><Field label="Employee number"><input required value={teacher.employee_number} onChange={e=>setTeacher({...teacher,employee_number:e.target.value})}/></Field><Field label="Email address"><input required type="email" value={teacher.email} onChange={e=>setTeacher({...teacher,email:e.target.value})}/></Field><Field label="Department"><select required value={teacher.department_id} onChange={e=>setTeacher({...teacher,department_id:e.target.value})}><option value="">Choose department</option>{departments.data?.map(d=><option key={d.id} value={d.id}>{d.name} ({d.code})</option>)}</select></Field><div className="form-action"><button className="button button-primary" disabled={!departments.data?.length}><Plus size={16}/> Create teacher</button></div></form></Card></div>
 <Card className="data-card"><div className="card-heading data-heading"><div><span className="eyebrow">ACCOUNT DIRECTORY</span><h2>Students and teachers</h2><p>Passwords are never shown. Account activation is completed by each account owner.</p></div><label className="search-box"><Search size={16}/><input aria-label="Search people" placeholder="Search ID, name or email" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <div className="table-wrap"><table><thead><tr><th>Person</th><th>Campus ID</th><th>Department</th><th>Account</th><th>Face template</th><th>Actions</th></tr></thead><tbody>
 {(students.data?.items||[]).map(r=><tr key={r.id}><td><strong>{r.full_name}</strong><small className="cell-sub">{r.email}</small></td><td>{r.student_number}</td><td>{departments.data?.find(d=>d.id===r.department_id)?.name||'—'}</td><td><Badge tone={!r.active?'danger':r.activated?'success':'warning'}>{!r.active?'Inactive':r.activated?'Active':'Invited'}</Badge></td><td><Badge tone={r.face_enrolled?'success':'neutral'}>{r.face_enrolled?'Enrolled':'Not enrolled'}</Badge></td><td><div className="row-actions"><button className="icon-button" title="Edit student" onClick={()=>setEditStudent({...r})}><Pencil size={15}/></button><button className="text-action" onClick={()=>void reset(r.user_id)}>Reset password</button>{r.face_enrolled&&<button className="text-action danger-text" onClick={()=>void deleteTemplate(r)}>Delete face</button>}<button className="text-action danger-text" onClick={()=>void status(r.user_id,r.active)}>{r.active?'Deactivate':'Reactivate'}</button></div></td></tr>)}
 {(teachers.data?.items||[]).map(r=><tr key={r.id}><td><strong>{r.full_name}</strong><small className="cell-sub">{r.email} · Teacher</small></td><td>{r.employee_number}</td><td>{departments.data?.find(d=>d.id===r.department_id)?.name||'—'}</td><td><Badge tone={!r.active?'danger':r.activated?'success':'warning'}>{!r.active?'Inactive':r.activated?'Active':'Invited'}</Badge></td><td>—</td><td><div className="row-actions"><button className="icon-button" title="Edit teacher" onClick={()=>setEditTeacher({...r})}><Pencil size={15}/></button><button className="text-action" onClick={()=>void reset(r.user_id)}>Reset password</button><button className="text-action danger-text" onClick={()=>void status(r.user_id,r.active)}>{r.active?'Deactivate':'Reactivate'}</button></div></td></tr>)}
 </tbody></table></div>{!students.data?.items.length&&!teachers.data?.items.length&&<EmptyState title="No matching accounts" message={search?'Try a different search.':'Accounts you create will appear here.'}/>}</Card>
 {editStudent&&<Modal title="Edit student record" onClose={()=>setEditStudent(null)}><form className="form-grid" onSubmit={saveStudent}><Field label="Full name"><input required value={editStudent.full_name} onChange={e=>setEditStudent({...editStudent,full_name:e.target.value})}/></Field><Field label="Email"><input required type="email" value={editStudent.email} onChange={e=>setEditStudent({...editStudent,email:e.target.value})}/></Field><Field label="Student ID"><input required value={editStudent.student_number} onChange={e=>setEditStudent({...editStudent,student_number:e.target.value})}/></Field><Field label="Department"><select value={editStudent.department_id} onChange={e=>setEditStudent({...editStudent,department_id:e.target.value})}>{departments.data?.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></Field><Field label="Program"><input value={editStudent.program} onChange={e=>setEditStudent({...editStudent,program:e.target.value})}/></Field><div className="form-action"><button className="button button-primary">Save student</button></div></form></Modal>}
 {editTeacher&&<Modal title="Edit teacher record" onClose={()=>setEditTeacher(null)}><form className="form-grid" onSubmit={saveTeacher}><Field label="Full name"><input required value={editTeacher.full_name} onChange={e=>setEditTeacher({...editTeacher,full_name:e.target.value})}/></Field><Field label="Email"><input required type="email" value={editTeacher.email} onChange={e=>setEditTeacher({...editTeacher,email:e.target.value})}/></Field><Field label="Employee number"><input required value={editTeacher.employee_number} onChange={e=>setEditTeacher({...editTeacher,employee_number:e.target.value})}/></Field><Field label="Department"><select value={editTeacher.department_id} onChange={e=>setEditTeacher({...editTeacher,department_id:e.target.value})}>{departments.data?.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></Field><div className="form-action"><button className="button button-primary">Save teacher</button></div></form></Modal>}
 </main>;
}

export function AcademicsPage(){
 const qc=useQueryClient();const [error,setError]=useState('');const [message,setMessage]=useState('');const [editingCourse,setEditingCourse]=useState<Course|null>(null);
 const departments=useQuery({queryKey:['admin-departments'],queryFn:()=>api<Department[]>('/admin/departments')});const years=useQuery({queryKey:['admin-years'],queryFn:()=>api<Year[]>('/admin/academic-years')});const semesters=useQuery({queryKey:['admin-semesters'],queryFn:()=>api<Semester[]>('/admin/semesters')});const courses=useQuery({queryKey:['admin-courses'],queryFn:()=>api<Course[]>('/admin/courses')});const sections=useQuery({queryKey:['admin-sections'],queryFn:()=>api<Section[]>('/admin/sections')});const students=useQuery({queryKey:['admin-students'],queryFn:()=>api<{items:StudentRow[]}>('/admin/students?limit=200')});const teachers=useQuery({queryKey:['admin-teachers'],queryFn:()=>api<{items:TeacherRow[]}>('/admin/teachers?limit=200')});const policy=useQuery({queryKey:['admin-settings'],queryFn:()=>api<{low_attendance_threshold:number}>('/admin/settings')});
 const [dep,setDep]=useState({name:'',code:''});const [year,setYear]=useState({name:'',starts_on:'',ends_on:'',active:true});const [semester,setSemester]=useState({academic_year_id:'',name:'',starts_on:'',ends_on:''});const [course,setCourse]=useState({department_id:'',semester_id:'',course_code:'',name:'',description:'',attendance_threshold:75});const [section,setSection]=useState({course_id:'',name:''});const [enrollment,setEnrollment]=useState({student_id:'',course_id:'',section_id:''});const [assignment,setAssignment]=useState({teacher_id:'',course_id:'',section_id:''});
 useEffect(()=>{if(policy.data)setCourse(current=>current.course_code?current:{...current,attendance_threshold:policy.data.low_attendance_threshold});},[policy.data?.low_attendance_threshold]);
 if([departments,years,semesters,courses,sections,students,teachers,policy].some(q=>q.isLoading))return <Loading label="Loading academic catalog…"/>;
 async function create(path:string,data:unknown,label:string){setError('');setMessage('');try{await api(path,{method:'POST',body:jsonBody(data)});setMessage(label);for(const key of ['admin-departments','admin-years','admin-semesters','admin-courses','admin-sections','admin-students','admin-teachers'])await qc.invalidateQueries({queryKey:[key]});return true;}catch(e){setError(errorText(e));return false;}}
 async function saveCourse(e:FormEvent){e.preventDefault();if(!editingCourse)return;try{await api(`/admin/courses/${editingCourse.id}`,{method:'PATCH',body:jsonBody({name:editingCourse.name,attendance_threshold:editingCourse.attendance_threshold,active:editingCourse.active})});setEditingCourse(null);setMessage('Course settings updated.');await qc.invalidateQueries({queryKey:['admin-courses']});}catch(err){setError(errorText(err));}}
 return <main><PageHeader eyebrow="ACADEMIC CONFIGURATION" title="Academic setup" description="Set up departments, years, semesters, courses, sections, enrollment and teacher assignments."/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
 <div className="setup-grid">
 <Card><PanelTitle icon={<BookOpen size={17}/>} eyebrow="ORGANIZATION" title="Departments" count={departments.data?.length}/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create('/admin/departments',{name:dep.name,code:dep.code},'Department created.').then(ok=>ok&&setDep({name:'',code:''}));}}><Field label="Department name"><input required value={dep.name} onChange={e=>setDep({...dep,name:e.target.value})}/></Field><Field label="Short code"><input required maxLength={30} value={dep.code} onChange={e=>setDep({...dep,code:e.target.value})}/></Field><button className="button button-primary"><Plus size={15}/> Add department</button></form><div className="simple-list">{departments.data?.map(d=><div key={d.id}><strong>{d.name}</strong><Badge>{d.code}</Badge></div>)}</div></Card>
 <Card><PanelTitle icon={<CalendarDays size={17}/>} eyebrow="ACADEMIC CALENDAR" title="Academic years" count={years.data?.length}/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create('/admin/academic-years',year,'Academic year created.').then(ok=>ok&&setYear({name:'',starts_on:'',ends_on:'',active:true}));}}><Field label="Year label"><input required placeholder="2026–2027" value={year.name} onChange={e=>setYear({...year,name:e.target.value})}/></Field><div className="form-two"><Field label="Starts"><input type="date" required value={year.starts_on} onChange={e=>setYear({...year,starts_on:e.target.value})}/></Field><Field label="Ends"><input type="date" required value={year.ends_on} onChange={e=>setYear({...year,ends_on:e.target.value})}/></Field></div><label className="check-row"><input type="checkbox" checked={year.active} onChange={e=>setYear({...year,active:e.target.checked})}/> Set as active year</label><button className="button button-primary"><Plus size={15}/> Add year</button></form><div className="simple-list">{years.data?.map(y=><div key={y.id}><strong>{y.name}</strong><span>{y.starts_on} — {y.ends_on}</span>{y.active&&<Badge tone="success">Active</Badge>}</div>)}</div></Card>
 <Card><PanelTitle icon={<CalendarDays size={17}/>} eyebrow="TERM" title="Semesters" count={semesters.data?.length}/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create('/admin/semesters',semester,'Semester created.').then(ok=>ok&&setSemester({academic_year_id:'',name:'',starts_on:'',ends_on:''}));}}><Field label="Academic year"><select required value={semester.academic_year_id} onChange={e=>setSemester({...semester,academic_year_id:e.target.value})}><option value="">Choose year</option>{years.data?.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></Field><Field label="Semester"><input required value={semester.name} onChange={e=>setSemester({...semester,name:e.target.value})} placeholder="Fall semester"/></Field><div className="form-two"><Field label="Starts"><input type="date" required value={semester.starts_on} onChange={e=>setSemester({...semester,starts_on:e.target.value})}/></Field><Field label="Ends"><input type="date" required value={semester.ends_on} onChange={e=>setSemester({...semester,ends_on:e.target.value})}/></Field></div><button className="button button-primary" disabled={!years.data?.length}><Plus size={15}/> Add semester</button></form><div className="simple-list">{semesters.data?.map(s=><div key={s.id}><strong>{s.name}</strong><span>{years.data?.find(y=>y.id===s.academic_year_id)?.name}</span></div>)}</div></Card>
 <Card><PanelTitle icon={<BookOpen size={17}/>} eyebrow="COURSE CATALOG" title="Courses" count={courses.data?.length}/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create('/admin/courses',{...course,semester_id:course.semester_id||null},'Course created.').then(ok=>ok&&setCourse({department_id:'',semester_id:'',course_code:'',name:'',description:'',attendance_threshold:policy.data?.low_attendance_threshold??75}));}}><div className="form-two"><Field label="Department"><select required value={course.department_id} onChange={e=>setCourse({...course,department_id:e.target.value})}><option value="">Choose</option>{departments.data?.map(d=><option key={d.id} value={d.id}>{d.code} · {d.name}</option>)}</select></Field><Field label="Semester"><select value={course.semester_id} onChange={e=>setCourse({...course,semester_id:e.target.value})}><option value="">No semester</option>{semesters.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div><div className="form-two"><Field label="Course code"><input required value={course.course_code} onChange={e=>setCourse({...course,course_code:e.target.value})}/></Field><Field label="Course name"><input required value={course.name} onChange={e=>setCourse({...course,name:e.target.value})}/></Field></div><Field label="Required attendance (%)"><input required type="number" min="0" max="100" value={course.attendance_threshold} onChange={e=>setCourse({...course,attendance_threshold:Number(e.target.value)})}/></Field><button className="button button-primary" disabled={!departments.data?.length}><Plus size={15}/> Add course</button></form><div className="simple-list">{courses.data?.map(c=><div key={c.id}><strong>{c.course_code} · {c.name}</strong><Badge tone={c.active?'info':'neutral'}>{c.attendance_threshold}%{!c.active?' · inactive':''}</Badge><button className="text-action" onClick={()=>setEditingCourse({...c})}>Edit</button></div>)}</div></Card>
 <Card><PanelTitle icon={<BookOpen size={17}/>} eyebrow="CLASS GROUPS" title="Sections" count={sections.data?.length}/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create(`/admin/courses/${section.course_id}/sections`,{name:section.name},'Section created.').then(ok=>ok&&setSection({course_id:'',name:''}));}}><Field label="Course"><select required value={section.course_id} onChange={e=>setSection({...section,course_id:e.target.value})}><option value="">Choose course</option>{courses.data?.map(c=><option key={c.id} value={c.id}>{c.course_code} · {c.name}</option>)}</select></Field><Field label="Section name"><input required placeholder="Section A" value={section.name} onChange={e=>setSection({...section,name:e.target.value})}/></Field><button className="button button-primary"><Plus size={15}/> Add section</button></form><div className="simple-list">{sections.data?.map(s=><div key={s.id}><strong>{courses.data?.find(c=>c.id===s.course_id)?.course_code} · {s.name}</strong></div>)}</div></Card>
 </div><div className="grid-two assignment-grid">
 <Card><PanelTitle icon={<UserPlus size={17}/>} eyebrow="STUDENT ROSTER" title="Enroll student"/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create('/admin/enrollments',{...enrollment,section_id:enrollment.section_id||null},'Student enrolled.').then(ok=>ok&&setEnrollment({student_id:'',course_id:'',section_id:''}));}}><Field label="Student"><select required value={enrollment.student_id} onChange={e=>setEnrollment({...enrollment,student_id:e.target.value})}><option value="">Choose student</option>{students.data?.items.map(s=><option key={s.id} value={s.id}>{s.student_number} · {s.full_name}</option>)}</select></Field><Field label="Course"><select required value={enrollment.course_id} onChange={e=>setEnrollment({...enrollment,course_id:e.target.value,section_id:''})}><option value="">Choose course</option>{courses.data?.map(c=><option key={c.id} value={c.id}>{c.course_code} · {c.name}</option>)}</select></Field><Field label="Section"><select value={enrollment.section_id} onChange={e=>setEnrollment({...enrollment,section_id:e.target.value})}><option value="">All sections</option>{sections.data?.filter(s=>s.course_id===enrollment.course_id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><button className="button button-primary"><Plus size={15}/> Enroll student</button></form></Card>
 <Card><PanelTitle icon={<Users size={17}/>} eyebrow="TEACHING ACCESS" title="Assign teacher"/><form className="compact-form" onSubmit={e=>{e.preventDefault();void create('/admin/teacher-assignments',{...assignment,section_id:assignment.section_id||null},'Teacher assigned.').then(ok=>ok&&setAssignment({teacher_id:'',course_id:'',section_id:''}));}}><Field label="Teacher"><select required value={assignment.teacher_id} onChange={e=>setAssignment({...assignment,teacher_id:e.target.value})}><option value="">Choose teacher</option>{teachers.data?.items.map(t=><option key={t.id} value={t.id}>{t.employee_number} · {t.full_name}</option>)}</select></Field><Field label="Course"><select required value={assignment.course_id} onChange={e=>setAssignment({...assignment,course_id:e.target.value,section_id:''})}><option value="">Choose course</option>{courses.data?.map(c=><option key={c.id} value={c.id}>{c.course_code} · {c.name}</option>)}</select></Field><Field label="Section"><select value={assignment.section_id} onChange={e=>setAssignment({...assignment,section_id:e.target.value})}><option value="">All sections</option>{sections.data?.filter(s=>s.course_id===assignment.course_id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><button className="button button-primary"><Plus size={15}/> Assign teacher</button></form></Card></div>
 {editingCourse&&<Modal title={`Edit ${editingCourse.course_code}`} onClose={()=>setEditingCourse(null)}><form className="form-grid" onSubmit={saveCourse}><Field label="Course name"><input required value={editingCourse.name} onChange={e=>setEditingCourse({...editingCourse,name:e.target.value})}/></Field><Field label="Required attendance (%)"><input type="number" min="0" max="100" value={editingCourse.attendance_threshold} onChange={e=>setEditingCourse({...editingCourse,attendance_threshold:Number(e.target.value)})}/></Field><label className="check-row"><input type="checkbox" checked={editingCourse.active} onChange={e=>setEditingCourse({...editingCourse,active:e.target.checked})}/> Course is active</label><div className="form-action"><button className="button button-primary">Save course</button></div></form></Modal>}
 </main>;
}
