import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, ArrowRight, BookOpen, Camera, Check, CheckCircle2, CircleHelp, Clock3, Download, Fingerprint, MapPin, RefreshCw, ShieldCheck, Trash2, Video, X } from 'lucide-react';
import { api, formatDate, formatPercent, formatTime, jsonBody } from '../lib/api';
import { Badge, Card, EmptyState, Field, Loading, Notice, PageHeader } from '../components/ui';
import { errorText, PanelTitle, statusTone } from './admin-shared';

interface SummaryCourse { course_id:string;course_code:string;course_name:string;threshold:number;total_eligible_sessions:number;present:number;late:number;absent:number;excused:number;attended:number;percentage:number|null;below_threshold:boolean }
interface EligibleSession { id:string;course_id:string;course_code:string;course_name:string;title:string;starts_at:string;ends_at:string;grace_minutes:number;location_name:string }
interface HistoryItem { id:string;session_id:string;course_id:string;course_code:string;course_name:string;status:string;marked_at:string;title:string;starts_at:string;correction_reason:string|null }
interface Profile { id:string;student_number:string;full_name:string;email:string;department_name:string|null;program:string;semester_id:string|null;enrollment_status:string;face_enrolled:boolean;face_enrolled_at:string|null;account_active:boolean }
interface Challenge { attempt_id:string;challenge_id:string;challenge_token:string;actions:string[];expires_at:string;maximum_frames:number }

export function MarkAttendancePage(){
 const qc=useQueryClient();const [params]=useSearchParams();const sessions=useQuery({queryKey:['eligible-sessions'],queryFn:()=>api<EligibleSession[]>('/attendance/sessions'),refetchInterval:30_000});const face=useQuery({queryKey:['face-status'],queryFn:()=>api<{ready:boolean;enrolled:boolean;biometric_storage_key_configured:boolean;models:Record<string,{file:string;installed:boolean;checksum_valid?:boolean}>}>('/face/status')});
 const [selected,setSelected]=useState(params.get('session')||'');const [phase,setPhase]=useState<'ready'|'challenge'|'submitting'|'success'>('ready');const [challenge,setChallenge]=useState<Challenge|null>(null);const [progress,setProgress]=useState(0);const [frameCount,setFrameCount]=useState(0);const [message,setMessage]=useState('');const [error,setError]=useState('');const [result,setResult]=useState<{status:string;marked_at:string}|null>(null);const [stream,setStream]=useState<MediaStream|null>(null);
 const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const stopRef=useRef(false);const doneRef=useRef(false);
 useEffect(()=>{if(videoRef.current&&stream){videoRef.current.srcObject=stream;void videoRef.current.play().catch(()=>setError('Camera preview could not start. Check browser camera permission.'));}},[stream]);
 const stopCamera=useCallback(()=>{stopRef.current=true;setStream(current=>{current?.getTracks().forEach(track=>track.stop());return null;});},[]);
 useEffect(()=>()=>{stream?.getTracks().forEach(track=>track.stop());},[stream]);
 const capture=useCallback(async()=>{
   const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||video.readyState<2)throw new Error('Camera is still starting. Keep the camera open and try again.');
   const width=Math.min(video.videoWidth,1280);const height=Math.round(video.videoHeight*(width/video.videoWidth));canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Camera capture is unavailable.');ctx.drawImage(video,0,0,width,height);
   return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not capture a camera frame.')),'image/jpeg',0.82));
 },[]);
 async function locate():Promise<{latitude:number;longitude:number;accuracy_m:number;measured_at:string}>{
   if(!navigator.geolocation)throw new Error('This browser does not support location. Try an up-to-date browser or contact your instructor.');
   return await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(position=>resolve({latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy_m:position.coords.accuracy,measured_at:new Date(position.timestamp).toISOString()}),cause=>{
     const msg=cause.code===1?'Location permission was denied. Allow location access for this site in your browser settings, then try again.':cause.code===2?'Your location is unavailable. Move to an open area and check device location settings.':'Location lookup timed out. Try again when GPS is available.';reject(new Error(msg));
   },{enableHighAccuracy:true,timeout:15000,maximumAge:0}));
 }
 async function begin(){setError('');setMessage('');setResult(null);doneRef.current=false;
   if(!selected){setError('Choose an eligible class session.');return;}
   if(!face.data?.biometric_storage_key_configured){setError('Biometric storage is not configured. Ask your administrator to restore the valid encryption key before trying again.');return;}
   if(face.data&&!face.data.enrolled){setError('Enroll your face from My profile before marking attendance.');return;}
   try{
     if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access requires a secure HTTPS page. Open SSAMS using the trusted campus link.');
     setMessage('Checking your location and class eligibility…');const position=await locate();
     const started=await api<Challenge>('/attendance/attempts',{method:'POST',body:jsonBody({session_id:selected,...position})});setChallenge(started);setProgress(0);setFrameCount(0);
     setMessage('Allow camera access, then follow the short blink and head-turn prompts.');
     const camera=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});stopRef.current=false;setStream(camera);setPhase('challenge');
   }catch(cause){setError(cause instanceof Error?cause.message:'Attendance could not be started.');setMessage('');setPhase('ready');}
 }
 const complete=useCallback(async(blob:Blob,active:Challenge)=>{if(doneRef.current)return;doneRef.current=true;setPhase('submitting');setMessage('Liveness completed. Verifying your enrolled face…');setError('');
   try{const form=new FormData();form.append('frame',blob,'live-frame.jpg');const idKey=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}-ssams`;const saved=await api<{status:string;marked_at:string;message:string}>(`/attendance/challenges/${active.challenge_id}/submit`,{method:'POST',headers:{'X-Liveness-Token':active.challenge_token,'Idempotency-Key':idKey},body:form});setResult(saved);setPhase('success');setMessage(saved.message);await qc.invalidateQueries({queryKey:['student-dashboard']});await qc.invalidateQueries({queryKey:['student-summary']});await qc.invalidateQueries({queryKey:['attendance-history']});await qc.invalidateQueries({queryKey:['eligible-sessions']});
   }catch(cause){doneRef.current=false;setPhase('ready');setError(cause instanceof Error?cause.message:'Face verification failed. Start a new attempt.');setMessage('');await qc.invalidateQueries({queryKey:['eligible-sessions']});}finally{stopCamera();setChallenge(null);}},[qc,stopCamera]);
 useEffect(()=>{
   if(phase!=='challenge'||!challenge||!stream)return;let cancelled=false;const activeChallenge=challenge;
   async function run(){while(!cancelled&&!stopRef.current){try{await new Promise(resolve=>window.setTimeout(resolve,360));if(cancelled||stopRef.current)return;const blob=await capture();const form=new FormData();form.append('frame',blob,'challenge-frame.jpg');const state=await api<{complete:boolean;progress:number;total:number;distinct_frames?:number;message?:string;error?:string}>(`/attendance/challenges/${activeChallenge.challenge_id}/frame`,{method:'POST',headers:{'X-Liveness-Token':activeChallenge.challenge_token},body:form});setProgress(state.progress);setFrameCount(state.distinct_frames||0);if(state.message)setMessage(state.message);if(state.error==='expired'||state.error==='frame_limit'){setError(state.message||'Challenge expired. Start again.');stopCamera();setChallenge(null);setPhase('ready');return;}if(state.complete){const final=await capture();await complete(final,activeChallenge);return;}}
     catch(cause){if(cancelled||stopRef.current)return;setError(cause instanceof Error?cause.message:'Could not process camera frame.');stopCamera();setChallenge(null);setPhase('ready');return;}}
   }
   void run();return()=>{cancelled=true;};
 },[phase,challenge,stream,capture,complete,stopCamera]);
 const activeSession=sessions.data?.find(s=>s.id===selected);const actionLabel=(key:string)=>({blink:'Blink both eyes',turn_left:'Turn your head to your left',turn_right:'Turn your head to your right',return_neutral:'Return to a neutral, forward-facing position'}[key]||key);
 const step=challenge?challenge.actions[Math.min(progress,challenge.actions.length-1)]:'';
 if(sessions.isLoading||face.isLoading)return <Loading label="Checking your account and class sessions…"/>;
 return <main><PageHeader eyebrow="STUDENT ATTENDANCE" title="Mark attendance" description="Attendance is recorded only after schedule, location, active liveness and face-match checks pass."/>
 {error&&<Notice kind="error">{error}</Notice>}{message&&!error&&phase!=='challenge'&&phase!=='submitting'&&<Notice kind={phase==='success'?'success':'info'}>{message}</Notice>}
 {!face.data?.ready&&<Notice kind="error">Local face model weights are missing or have not passed checksum validation. Attendance cannot be accepted until an administrator installs them.</Notice>}{!face.data?.biometric_storage_key_configured&&<Notice kind="error">Biometric encryption is not configured with a valid Fernet key. Attendance cannot be accepted until the administrator restores the correct key.</Notice>}
 {phase==='success'&&result?<Card className="success-result"><span className="success-check"><CheckCircle2 size={28}/></span><div><span className="eyebrow">ATTENDANCE RECORDED</span><h2>You’re checked in</h2><p>{activeSession?.course_code||''} · {activeSession?.course_name||'Class session'} · <Badge tone={result.status==='late'?'warning':'success'}>{result.status}</Badge></p><small>Recorded {formatDate(result.marked_at)} using the campus server clock.</small></div><Link to="/student/attendance" className="button button-secondary">View history</Link></Card>:null}
 {phase==='ready'&&<div className="attendance-flow-grid"><Card className="attendance-start-card"><span className="round-icon blue-icon"><Clock3 size={20}/></span><span className="eyebrow">CURRENTLY ELIGIBLE</span><h2>Choose your class</h2><p>Select an open session. The system checks enrollment, campus location, camera liveness and your enrolled face template on the server.</p>{sessions.data?.length?<><Field label="Eligible class session"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a class</option>{sessions.data.map(s=><option key={s.id} value={s.id}>{s.course_code} · {s.title} — {s.course_name}</option>)}</select></Field>{activeSession&&<div className="session-preview"><div><span>SESSION</span><strong>{activeSession.title}</strong><small>{activeSession.course_name}</small></div><div><span>LOCATION</span><strong><MapPin size={13}/>{activeSession.location_name}</strong><small>Window ends {formatDate(activeSession.ends_at)}</small></div></div>}<button className="button button-primary button-wide" onClick={()=>void begin()} disabled={!selected||!face.data?.ready||!face.data?.biometric_storage_key_configured||!face.data?.enrolled}><Camera size={17}/> Start secure verification</button></>:<EmptyState title="No open class sessions" message="An attendance session appears during its scheduled window after your administrator enrolls you."/>}
 {!face.data?.enrolled&&<div className="support-inline"><Fingerprint size={17}/><span>Face enrollment is required for attendance.</span><Link to="/student/profile">Enroll face <ArrowRightSmall/></Link></div>}
 <div className="sensor-permissions"><span><MapPin size={14}/> One location reading</span><span><Video size={14}/> Camera stream while verifying</span><span><ShieldCheck size={14}/> Frames are not saved</span></div></Card>
 <Card className="verification-info"><div className="card-heading"><div><span className="eyebrow">WHAT TO EXPECT</span><h2>Four checks. One secure record.</h2></div></div><ol className="step-list"><li><span>01</span><div><strong>Confirm your class and enrollment</strong><small>Only an active, assigned class session can be checked in.</small></div></li><li><span>02</span><div><strong>Verify classroom location</strong><small>Your device provides a timestamped GPS reading; the server calculates distance.</small></div></li><li><span>03</span><div><strong>Follow a randomized movement prompt</strong><small>Blink, turn your head and return to neutral while the camera is active.</small></div></li><li><span>04</span><div><strong>Match your encrypted face template</strong><small>A local model compares the live frame only to your own enrollment.</small></div></li></ol><Notice kind="info">Blink and head-turn checks are basic active liveness signals, not certified protection against replayed video or sophisticated spoofing.</Notice></Card></div>}
 {(phase==='challenge'||phase==='submitting')&&challenge&&<Card className="live-challenge-card"><div className="live-challenge-heading"><div><span className="eyebrow">LIVE VERIFICATION</span><h2>{phase==='submitting'?'Checking your face…':'Follow the camera prompt'}</h2><p>Keep only your face in frame. Your video stays in memory and is not recorded.</p></div><Badge tone="info">Expires {formatTime(challenge.expires_at)}</Badge></div><div className="camera-layout"><div className="camera-frame"><video ref={videoRef} autoPlay playsInline muted aria-label="Live camera preview"/><div className="camera-frame-overlay"><span className="camera-corner top-left"/><span className="camera-corner top-right"/><span className="camera-corner bottom-left"/><span className="camera-corner bottom-right"/></div>{phase==='submitting'&&<div className="camera-processing"><RefreshCw className="spin" size={22}/>Verifying on the campus server</div>}</div><div className="challenge-guidance"><span className="challenge-count">STEP {Math.min(progress+1,challenge.actions.length)} OF {challenge.actions.length}</span><h3>{actionLabel(step)}</h3><p>{message||'Look at the camera and follow the movement prompt.'}</p><div className="progress-steps">{challenge.actions.map((action,i)=><span key={`${action}-${i}`} className={i<progress?'step-done':i===progress?'step-current':''}>{i<progress?<Check size={13}/>:i+1}</span>)}</div><div className="camera-privacy"><ShieldCheck size={17}/><span>Local campus inference<br/><small>{frameCount} distinct frames analyzed</small></span></div><button className="button button-secondary" disabled={phase==='submitting'} onClick={()=>{stopCamera();setChallenge(null);setPhase('ready');setMessage('Verification cancelled. Start again when ready.');}}><X size={16}/> Cancel verification</button></div></div><canvas ref={canvasRef} className="sr-only"/></Card>}
 <div className="attendance-footnote"><CircleHelp size={15}/><span>Location can be inaccurate indoors or spoofed by a device. For a correction or access issue, submit a review request or talk to your instructor.</span></div>
 </main>;
}

export function StudentAttendancePage(){
 const [params,setParams]=useSearchParams();const [courseFilter,setCourseFilter]=useState(params.get('course')||'');const [status,setStatus]=useState('');const summary=useQuery({queryKey:['student-summary'],queryFn:()=>api<{courses:SummaryCourse[];overall_percentage:number|null;eligible_sessions:number;attended:number}>('/attendance/summary')});const history=useQuery({queryKey:['attendance-history',courseFilter,status],queryFn:()=>api<{items:HistoryItem[];total:number}>(`/attendance/history?limit=200${courseFilter?`&course_id=${courseFilter}`:''}${status?`&status=${status}`:''}`)});
 if(summary.isLoading||history.isLoading)return <Loading label="Loading your attendance history…"/>;
 return <main><PageHeader eyebrow="STUDENT RECORDS" title="My attendance" description="Course-wise percentages and recorded session history." actions={<a className="button button-secondary" href="/api/v1/reports/attendance.csv"><Download size={16}/> Download CSV</a>}/><div className="stats-grid compact-stats"><div className="stat-card"><div className="stat-top"><span>Overall attendance</span><ChartGlyph/></div><strong>{formatPercent(summary.data?.overall_percentage)}</strong><small>{summary.data?.attended||0} of {summary.data?.eligible_sessions||0} eligible sessions</small></div>{summary.data?.courses.slice(0,3).map(c=><div className="stat-card" key={c.course_id}><div className="stat-top"><span>{c.course_code}</span><BookOpen size={17}/></div><strong className={c.percentage!==null&&c.percentage<c.threshold?'text-danger':''}>{formatPercent(c.percentage)}</strong><small>{c.present} present · {c.late} late · {c.absent} absent</small></div>)}</div>
 <Card className="data-card"><div className="filter-bar"><label className="field"><span className="field-label">Course</span><select value={courseFilter} onChange={e=>{setCourseFilter(e.target.value);if(e.target.value)setParams({course:e.target.value});else setParams({});}}><option value="">All courses</option>{summary.data?.courses.map(c=><option key={c.course_id} value={c.course_id}>{c.course_code} · {c.course_name}</option>)}</select></label><label className="field"><span className="field-label">Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['present','late','absent','excused'].map(s=><option key={s}>{s}</option>)}</select></label><div className="filter-count"><strong>{history.data?.total||0}</strong> records</div></div>{history.data?.items.length?<div className="table-wrap"><table><thead><tr><th>Class</th><th>Course</th><th>Status</th><th>Recorded</th><th>Review</th></tr></thead><tbody>{history.data.items.map(r=><tr key={r.id}><td><strong>{r.title}</strong><small className="cell-sub">Session {r.session_id.slice(0,8)}</small></td><td><strong>{r.course_code}</strong><small className="cell-sub">{r.course_name}</small></td><td><Badge tone={statusTone(r.status)}>{r.status}</Badge></td><td>{formatDate(r.marked_at)}</td><td>{r.correction_reason||<Link className="text-link" to="/student/corrections">Request review</Link>}</td></tr>)}</tbody></table></div>:<EmptyState title="No attendance records" message="Use Mark attendance during an open class session. Absences appear after a session is finalized."/>}</Card>
 <div className="course-summary-grid">{summary.data?.courses.map(c=><Card className="course-summary-card" key={c.course_id}><div className="course-summary-top"><span className="course-mark">{c.course_code.slice(0,2)}</span><Badge tone={c.below_threshold?'warning':'success'}>{c.below_threshold?'Below threshold':'On track'}</Badge></div><h3>{c.course_code}</h3><p>{c.course_name}</p><div className="summary-percent"><strong>{formatPercent(c.percentage)}</strong><span>Required {c.threshold}%</span></div><div className="summary-progress"><i style={{width:`${Math.min(100,c.percentage||0)}%`}}/></div><small>{c.attended} attended of {c.total_eligible_sessions} eligible sessions · {c.absent} absent · {c.excused} excused</small></Card>)}</div>
 </main>;
}

export function StudentProfilePage(){
 const qc=useQueryClient();const profile=useQuery({queryKey:['student-profile'],queryFn:()=>api<Profile>('/student/profile')});const face=useQuery({queryKey:['face-status'],queryFn:()=>api<{ready:boolean;enrolled:boolean;enrolled_at:string|null;provider:string;biometric_storage_key_configured:boolean;models:Record<string,{file:string;installed:boolean;checksum_valid?:boolean}>}>('/face/status')});
 const [stream,setStream]=useState<MediaStream|null>(null);const [frames,setFrames]=useState<Blob[]>([]);const [consent,setConsent]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const lastCapture=useRef(0);
 useEffect(()=>{if(videoRef.current&&stream){videoRef.current.srcObject=stream;void videoRef.current.play().catch(()=>setError('Camera preview could not start.'));}},[stream]);
 const stop=useCallback(()=>{setStream(s=>{s?.getTracks().forEach(t=>t.stop());return null;});},[]);useEffect(()=>()=>stream?.getTracks().forEach(t=>t.stop()),[stream]);
 async function openCamera(){setError('');if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setError('Camera access requires a secure HTTPS page. Use the trusted campus link.');return;}try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});setFrames([]);setStream(media);}catch{setError('Camera permission was denied or no camera is available. Allow camera access in browser settings.');}}
 async function capture(){try{const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||video.readyState<2)throw new Error('Camera is still starting.');if(Date.now()-lastCapture.current<700)throw new Error('Wait briefly between enrollment samples and vary your pose slightly.');const w=Math.min(video.videoWidth,1280),h=Math.round(video.videoHeight*w/video.videoWidth);canvas.width=w;canvas.height=h;canvas.getContext('2d')?.drawImage(video,0,0,w,h);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Frame capture failed.')),'image/jpeg',0.84));lastCapture.current=Date.now();setFrames(current=>[...current,blob].slice(0,3));setError('');}catch(e){setError(e instanceof Error?e.message:'Could not capture a frame.');}}
 async function enroll(e:FormEvent){e.preventDefault();setError('');if(frames.length!==3){setError('Capture three separate frames first.');return;}if(!consent){setError('You must agree to the biometric notice before enrolling.');return;}setBusy(true);try{const form=new FormData();frames.forEach((frame,i)=>form.append('frames',frame,`enrollment-${i+1}.jpg`));form.append('consent','true');await api('/face/enroll',{method:'POST',body:form});setMessage('Face template enrolled. Raw sample frames were discarded.');setFrames([]);setConsent(false);stop();await qc.invalidateQueries({queryKey:['face-status']});await qc.invalidateQueries({queryKey:['student-profile']});}catch(err){setError(errorText(err));}finally{setBusy(false);}}
 async function remove(){if(!window.confirm('Delete your encrypted face template? Attendance will require enrollment again.'))return;try{await api('/face/enrollment',{method:'DELETE'});setMessage('Face template removed.');await qc.invalidateQueries({queryKey:['face-status']});await qc.invalidateQueries({queryKey:['student-profile']});}catch(err){setError(errorText(err));}}
 if(profile.isLoading||face.isLoading)return <Loading label="Loading your profile…"/>;const p=profile.data!;const f=face.data!;
 return <main><PageHeader eyebrow="STUDENT PROFILE" title="My profile" description="Your student ID and managed account details. Contact an administrator to change privileged fields."/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
 <div className="grid-two"><Card><div className="profile-hero"><span className="profile-avatar-large">{p.full_name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><div><span className="eyebrow">STUDENT ACCOUNT</span><h2>{p.full_name}</h2><p>{p.student_number}</p></div><Badge tone={p.account_active?'success':'danger'}>{p.account_active?'Active':'Inactive'}</Badge></div><div className="profile-details"><div><span>Email</span><strong>{p.email}</strong></div><div><span>Department</span><strong>{p.department_name||'—'}</strong></div><div><span>Program</span><strong>{p.program||'—'}</strong></div><div><span>Enrollment status</span><strong>{p.enrollment_status}</strong></div></div><p className="inline-hint">For profile changes or account support, contact your SSAMS administrator. Your role and student ID are managed centrally.</p></Card>
 <Card className="face-enroll-card"><div className="card-heading"><div><span className="eyebrow">BIOMETRIC ENROLLMENT</span><h2>Face template</h2></div><span className="round-icon purple-icon"><Fingerprint size={19}/></span></div>{f.enrolled?<><Notice kind="success">Face enrollment is active{f.enrolled_at?` · ${formatDate(f.enrolled_at)}`:''}.</Notice>{!f.biometric_storage_key_configured&&<Notice kind="error">The encryption key is unavailable or invalid. Ask an administrator to restore the original key; do not generate a replacement for this database.</Notice>}<p className="card-intro">A protected face representation is used only to compare your live attendance frame to your own profile. Raw camera frames are not kept.</p><button className="button button-secondary danger-outline" onClick={()=>void remove()}><Trash2 size={16}/> Delete my face template</button></>:<><p className="card-intro">Enrollment captures three separate frames, checks face visibility, lighting, pose and consistency, then stores only an encrypted representation.</p>{!f.ready&&<Notice kind="error">Local model weights are missing or have not passed checksum validation. Ask an administrator to complete model setup.</Notice>}{!f.biometric_storage_key_configured&&<Notice kind="error">The biometric encryption key is missing or invalid. Ask an administrator to correct the private key configuration.</Notice>}
 {!stream?<button className="button button-primary" disabled={!f.ready||!f.biometric_storage_key_configured} onClick={()=>void openCamera()}><Camera size={16}/> Open camera</button>:<><div className="enroll-camera"><video ref={videoRef} autoPlay playsInline muted aria-label="Face enrollment camera preview"/><div className="camera-frame-overlay"><span className="camera-corner top-left"/><span className="camera-corner top-right"/><span className="camera-corner bottom-left"/><span className="camera-corner bottom-right"/></div></div><canvas ref={canvasRef} className="sr-only"/><div className="sample-counter">{frames.length} of 3 live samples captured</div><div className="sample-dots">{[0,1,2].map(i=><span key={i} className={i<frames.length?'sample-done':''}>{i<frames.length?<Check size={13}/>:i+1}</span>)}</div><div className="button-row"><button className="button button-secondary" type="button" disabled={frames.length>=3} onClick={()=>void capture()}><Camera size={16}/> Capture sample</button><button className="button button-secondary" type="button" onClick={()=>{stop();setFrames([]);}}>Stop camera</button></div><form onSubmit={enroll}><label className="consent-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I consent to collection and encrypted storage of my face template to verify attendance. I have read the <Link to="/privacy">biometric data notice</Link>. I understand I may request deletion or appeal verification results.</span></label><button className="button button-primary button-wide" disabled={frames.length!==3||!consent||busy}>{busy?'Checking samples…':'Enroll encrypted face template'}</button></form></>}
 <div className="privacy-callout"><ShieldCheck size={16}/><span>No raw selfie is retained. Biometric recognition is sensitive data; institutional approval, retention and appeal policies apply.</span></div></>}</Card></div>
 </main>;
}

export function StudentCorrectionsPage(){
 const qc=useQueryClient();const history=useQuery({queryKey:['attendance-history'],queryFn:()=>api<{items:HistoryItem[]}>('/attendance/history?limit=200')});const requests=useQuery({queryKey:['student-corrections'],queryFn:()=>api<Array<{id:string;session_id:string;course_name:string;requested_status:string;reason:string;status:string;decision_reason:string|null;created_at:string}>>('/student/corrections')});const [sessionId,setSessionId]=useState('');const [status,setStatus]=useState('present');const [reason,setReason]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');try{await api('/student/corrections',{method:'POST',body:jsonBody({session_id:sessionId,requested_status:status,reason})});setMessage('Your request was submitted for review.');setReason('');await qc.invalidateQueries({queryKey:['student-corrections']});}catch(err){setError(errorText(err));}}
 if(history.isLoading||requests.isLoading)return <Loading label="Loading correction history…"/>;const past=history.data?.items||[];
 return <main><PageHeader eyebrow="STUDENT SUPPORT" title="Correction requests" description="Dispute a recorded attendance status. A teacher or administrator will review your request."/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}<div className="grid-two"><Card><PanelTitle icon={<AlertCircle size={17}/>} eyebrow="SUBMIT A DISPUTE" title="Request an attendance review"/><form className="form-grid" onSubmit={submit}><Field label="Recorded class session"><select required value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">Choose a recorded class</option>{past.map(item=><option key={item.session_id} value={item.session_id}>{item.course_code} · {item.title} · {formatDate(item.marked_at)} · {item.status}</option>)}</select></Field><Field label="Requested status"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="present">Present</option><option value="late">Late</option><option value="excused">Excused</option></select></Field><Field label="Reason for review"><textarea required minLength={5} maxLength={1000} rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what should be reviewed. Do not include unnecessary sensitive personal details."/></Field><button className="button button-primary"><Check size={16}/> Submit review request</button></form>{!past.length&&<p className="inline-hint">There are no recorded past sessions to dispute. Ask your instructor if a class is missing.</p>}</Card>
 <Card><PanelTitle icon={<ShieldCheck size={17}/>} eyebrow="FAIR REVIEW" title="What happens next"/><ol className="step-list"><li><span>01</span><div><strong>Your request is linked to one class</strong><small>Only your own enrolled session can be disputed.</small></div></li><li><span>02</span><div><strong>A teacher or administrator reviews the reason</strong><small>Course teachers may review only their assigned students and sessions.</small></div></li><li><span>03</span><div><strong>Any approved change is audited</strong><small>The attendance record keeps its correction reason and the reviewer identity.</small></div></li></ol><Notice kind="info">Do not attach medical documents here. Contact your institution for a secure process if supporting documentation is needed.</Notice></Card></div>
 <Card className="data-card"><div className="card-heading"><div><span className="eyebrow">REQUEST HISTORY</span><h2>My reviews</h2></div></div>{requests.data?.length?<div className="table-wrap"><table><thead><tr><th>Course</th><th>Requested</th><th>Reason</th><th>State</th><th>Submitted</th><th>Decision note</th></tr></thead><tbody>{requests.data.map(r=><tr key={r.id}><td>{r.course_name}<small className="cell-sub">{r.session_id.slice(0,8)}</small></td><td><Badge tone={statusTone(r.requested_status)}>{r.requested_status}</Badge></td><td>{r.reason}</td><td><Badge tone={statusTone(r.status)}>{r.status}</Badge></td><td>{formatDate(r.created_at)}</td><td>{r.decision_reason||'—'}</td></tr>)}</tbody></table></div>:<EmptyState title="No correction requests" message="Requests you submit will appear here."/>}</Card></main>;
}

function ChartGlyph(){return <BookOpen size={17}/>;}
function ArrowRightSmall(){return <ArrowRight size={13}/>;}
