import { useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { ArrowDownToLine, BookOpen, CalendarDays, Check, ClipboardCheck, ShieldCheck, X } from 'lucide-react';
import { api, formatDate, formatPercent, jsonBody } from '../lib/api';
import { Badge, Card, EmptyState, Field, Loading, Notice, PageHeader } from '../components/ui';
import { errorText, statusTone } from './admin-shared';
import type { CorrectionRow } from './admin-shared';

interface CourseRow{course_id:string;course_code:string;course_name:string;section_id:string|null;section_name:string;attendance_threshold:number}
interface ClassSession{ id:string;course_id:string;course_code:string;course_name:string;section_id:string|null;section_name:string;title:string;starts_at:string;ends_at:string;grace_minutes:number;cancelled:boolean }
interface RegisterStudent{student_id:string;student_number:string;student_name:string;attendance_status:string;marked_at:string|null;attendance_percentage:number|null;eligible_sessions:number}

export function TeacherClassesPage(){
 const [sessionId,setSessionId]=useState('');const [params]=useSearchParams();const courseFilter=params.get('course')||'';const courses=useQuery({queryKey:['teacher-courses'],queryFn:()=>api<CourseRow[]>('/teacher/courses')});const sessions=useQuery({queryKey:['teacher-sessions'],queryFn:()=>api<{items:ClassSession[];total:number}>('/teacher/sessions?limit=200')});const register=useQuery({queryKey:['teacher-register',sessionId],queryFn:()=>api<{session:ClassSession;students:RegisterStudent[];total:number}>(`/teacher/sessions/${sessionId}/register`),enabled:!!sessionId});
 if(courses.isLoading||sessions.isLoading)return <Loading label="Loading assigned classes…"/>;
 return <main><PageHeader eyebrow="TEACHER WORKSPACE" title="My classes" description="Attendance registers are restricted to your assigned courses and sections." actions={<a className="button button-secondary" href={`/api/v1/teacher/export.csv${sessionId?`?session_id=${sessionId}`:''}`}><ArrowDownToLine size={16}/> Export CSV</a>}/>{(courses.isError||sessions.isError)&&<Notice kind="error">Assigned classes could not be refreshed. Check the server connection and retry.</Notice>}
 <div className="stats-grid compact-stats"><div className="stat-card"><div className="stat-top"><span>Assigned courses</span><BookOpen size={17}/></div><strong>{courses.data?.length||0}</strong><small>Course/section assignments</small></div><div className="stat-card"><div className="stat-top"><span>Scheduled sessions</span><CalendarDays size={17}/></div><strong>{sessions.data?.total||0}</strong><small>Authorized class sessions</small></div></div>
 <Card className="data-card"><div className="filter-bar"><label className="field"><span className="field-label">Class session</span><select value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">Select a session register</option>{sessions.data?.items.filter(s=>!courseFilter||s.course_id===courseFilter).map(s=><option key={s.id} value={s.id}>{s.course_code} · {s.title} · {formatDate(s.starts_at)}</option>)}</select></label><span className="filter-count">{register.data?.total??0} students</span></div>
 {sessionId&&register.isLoading?<Loading label="Loading the authorized register…"/>:sessionId&&register.isError?<Notice kind="error">The class register could not be loaded. Check the session assignment and try again.</Notice>:sessionId&&register.data?<><div className="register-context"><div><span className="eyebrow">CLASS REGISTER</span><h2>{register.data.session.course_code} · {register.data.session.title}</h2><p>{register.data.session.course_name} · {register.data.session.section_name} · {formatDate(register.data.session.starts_at)}</p></div><Badge tone={register.data.session.cancelled?'danger':'info'}>{register.data.session.cancelled?'Cancelled':'Scheduled'}</Badge></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Status</th><th>Attendance %</th><th>Eligible sessions</th><th>Recorded</th></tr></thead><tbody>{register.data.students.map(r=><tr key={r.student_id}><td><strong>{r.student_name}</strong><small className="cell-sub">{r.student_number}</small></td><td><Badge tone={statusTone(r.attendance_status)}>{r.attendance_status}</Badge></td><td>{formatPercent(r.attendance_percentage)}</td><td>{r.eligible_sessions}</td><td>{r.marked_at?formatDate(r.marked_at):'—'}</td></tr>)}</tbody></table></div>{!register.data.students.length&&<EmptyState title="No students in this section" message="Ask an administrator to review course enrollments."/>}</>:<EmptyState title="Choose an assigned class session" message="Select a session above to see its roster and attendance results."/>}</Card>
 <Card className="data-card"><div className="card-heading"><div><span className="eyebrow">MY COURSE ACCESS</span><h2>Authorized courses</h2></div></div>{courses.data?.length?<div className="course-list">{courses.data.map(c=><div className="course-row" key={`${c.course_id}-${c.section_id}`}><span className="course-mark purple-mark">{c.course_code.slice(0,2)}</span><span className="course-copy"><strong>{c.course_code} · {c.course_name}</strong><small>{c.section_name} · required {c.attendance_threshold}%</small></span></div>)}</div>:<EmptyState title="No courses assigned" message="An administrator can assign you to a course or section."/>}</Card>
 </main>;
}

export function TeacherWatchPage(){
 const courses=useQuery({queryKey:['teacher-courses'],queryFn:()=>api<CourseRow[]>('/teacher/courses')});const [courseId,setCourseId]=useState('');const rows=useQuery({queryKey:['teacher-watch',courseId],queryFn:()=>api<Array<{student_id:string;student_number:string;student_name:string;course_id:string;course_code:string;course_name:string;percentage:number|null;threshold:number;total_eligible_sessions:number;attended:number;absent:number;late:number}>>(`/teacher/low-attendance${courseId?`?course_id=${courseId}`:''}`)});
 if(courses.isLoading||rows.isLoading)return <Loading label="Loading attendance watch…"/>;
 return <main><PageHeader eyebrow="STUDENT SUPPORT" title="Attendance watch" description="Students below their configured course threshold in classes assigned to you." actions={<a className="button button-secondary" href={`/api/v1/teacher/export.csv${courseId?`?course_id=${encodeURIComponent(courseId)}`:''}`}><ArrowDownToLine size={16}/> Export records</a>}/><Card className="data-card"><div className="filter-bar"><label className="field"><span className="field-label">Course</span><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">All assigned courses</option>{courses.data?.map(c=><option key={c.course_id} value={c.course_id}>{c.course_code} · {c.course_name}</option>)}</select></label><span className="filter-count"><strong>{rows.data?.length||0}</strong> below threshold</span></div>
 {rows.isError?<Notice kind="error">Attendance watch could not be loaded. Check your assignment and try again.</Notice>:rows.data?.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Attendance</th><th>Required</th><th>Sessions</th><th>Present / late / absent</th></tr></thead><tbody>{rows.data.map(r=><tr key={`${r.student_id}-${r.course_id}`}><td><strong>{r.student_name}</strong><small className="cell-sub">{r.student_number}</small></td><td>{r.course_code}<small className="cell-sub">{r.course_name}</small></td><td><Badge tone="warning">{formatPercent(r.percentage)}</Badge></td><td>{r.threshold}%</td><td>{r.total_eligible_sessions}</td><td>{r.attended} / {r.late} / {r.absent}</td></tr>)}</tbody></table></div>:<EmptyState title="No students below threshold" message="Students are listed here when eligible course sessions exist and their attendance percentage is below the course requirement."/>}</Card></main>;
}

export function TeacherCorrectionsPage(){
 const qc=useQueryClient();const [error,setError]=useState('');const [message,setMessage]=useState('');const [status,setStatus]=useState('pending');const [sessionId,setSessionId]=useState('');const [studentId,setStudentId]=useState('');const [requestedStatus,setRequestedStatus]=useState('present');const [reason,setReason]=useState('');
 const requests=useQuery({queryKey:['teacher-corrections',status],queryFn:()=>api<CorrectionRow[]>(`/teacher/corrections?status=${status}`)});const sessions=useQuery({queryKey:['teacher-sessions'],queryFn:()=>api<{items:ClassSession[]}>('/teacher/sessions?limit=200')});const register=useQuery({queryKey:['teacher-register',sessionId],queryFn:()=>api<{students:RegisterStudent[]}>(`/teacher/sessions/${sessionId}/register`),enabled:!!sessionId});
 async function propose(e:FormEvent){e.preventDefault();setError('');try{await api('/teacher/corrections',{method:'POST',body:jsonBody({student_id:studentId,session_id:sessionId,requested_status:requestedStatus,reason})});setMessage('Correction proposal submitted for review.');setReason('');await qc.invalidateQueries({queryKey:['teacher-corrections']});}catch(err){setError(errorText(err));}}
 async function decide(r:CorrectionRow,approved:boolean){const note=window.prompt(approved?'Add an approval note:':'Add a reason for rejection:');if(note===null)return;if(note.trim().length<3){setError('Enter a short decision note.');return;}try{await api(`/teacher/corrections/${r.id}/resolve`,{method:'POST',body:jsonBody({approved,decision_reason:note})});setMessage(`Correction ${approved?'approved':'rejected'}.`);await qc.invalidateQueries({queryKey:['teacher-corrections']});await qc.invalidateQueries({queryKey:['teacher-register']});}catch(err){setError(errorText(err));}}
 if(requests.isLoading||sessions.isLoading)return <Loading label="Loading course correction requests…"/>;
 return <main><PageHeader eyebrow="REVIEW & DISPUTES" title="Correction requests" description="Review disputes for your assigned classes or submit a documented correction proposal." actions={<label className="filter-select"><span>Queue</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label>}/>{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}{requests.isError&&<Notice kind="error">Correction requests could not be loaded. Try refreshing this page.</Notice>}
 <div className="grid-two"><Card><div className="card-heading"><div><span className="eyebrow">TEACHER PROPOSAL</span><h2>Submit a status correction</h2></div><ClipboardCheck size={18}/></div><form className="form-grid" onSubmit={propose}><Field label="Assigned session"><select required value={sessionId} onChange={e=>{setSessionId(e.target.value);setStudentId('');}}><option value="">Choose session</option>{sessions.data?.items.filter(s=>!s.cancelled).map(s=><option key={s.id} value={s.id}>{s.course_code} · {s.title} · {formatDate(s.starts_at)}</option>)}</select></Field><Field label="Student in selected class"><select required value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Choose student</option>{register.data?.students.map(s=><option key={s.student_id} value={s.student_id}>{s.student_number} · {s.student_name}</option>)}</select></Field><Field label="Proposed status"><select value={requestedStatus} onChange={e=>setRequestedStatus(e.target.value)}>{['present','late','absent','excused'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Reason"><textarea required minLength={5} maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></Field><button className="button button-primary"><Check size={16}/> Submit proposal</button></form></Card><Card><div className="card-heading"><div><span className="eyebrow">REVIEW CHECKLIST</span><h2>Before deciding</h2></div><ShieldCheck size={18}/></div><ol className="step-list"><li><span>01</span><div><strong>Confirm the class and enrollment</strong><small>Only your assigned course sections can be reviewed.</small></div></li><li><span>02</span><div><strong>Read the submitter’s explanation</strong><small>Ask for evidence using your institution’s approved private process.</small></div></li><li><span>03</span><div><strong>Record a decision rationale</strong><small>Approved corrections update the attendance record and create an audit event.</small></div></li></ol></Card></div>
 <div className="correction-list">{requests.data?.map(r=><Card key={r.id} className="correction-item"><div className="correction-item-top"><Badge tone={statusTone(r.status)}>{r.status}</Badge><span className="correction-date">{formatDate(r.created_at)}</span></div><h2>{r.student_name} <small>({r.student_number})</small></h2><p className="correction-context">{r.course_name} · {r.session_id.slice(0,8)} · requested <Badge tone={statusTone(r.requested_status)}>{r.requested_status}</Badge></p><div className="correction-reason"><span>REASON</span><p>{r.reason}</p></div>{r.decision_reason&&<div className="review-note"><strong>Decision note</strong><p>{r.decision_reason}</p></div>}{r.status==='pending'&&<div className="correction-actions"><button className="button button-primary" onClick={()=>void decide(r,true)}><Check size={16}/> Approve & apply</button><button className="button button-secondary" onClick={()=>void decide(r,false)}><X size={16}/> Reject</button></div>}</Card>)}</div>{!requests.isError&&!requests.data?.length&&<Card><EmptyState title={`No ${status} requests`} message="Course-specific student disputes and teacher proposals will appear here."/></Card>}
 </main>;
}
